### ISSUE TITLE
PHPcs Issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#55]
File:
[PHPcs-ORG.zip](https://github.com/wpswings/woo-refund-and-exchange-lite/files/8541532/PHPcs-ORG.zip)
[PHPcs-PRO.zip](https://github.com/wpswings/woo-refund-and-exchange-lite/files/8541533/PHPcs-PRO.zip)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
some phpcs issues are not fixed 
the ORG must be with zero issues

**Comment by makewebbetter-com** [comment]
Still having same repeated issues
<?xml version="1.0" encoding="UTF-8"?>
<phpcs version="3.6.1">
<file name="/home/cedcoss/Desktop/woo-refund-and-exchange-lite-4.0.2/admin/class-woo-refund-and-exchange-lite-admin.php" errors="2" warnings="0" fixable="0">
    <error line="1159" column="39" source="WordPress.DB.PreparedSQL.NotPrepared" severity="5" fixable="0">Use placeholders and $wpdb-&gt;prepare(); found $sql</error>
    <error line="1218" column="9" source="WordPress.WP.GlobalVariablesOverride.Prohibited" severity="5" fixable="0">Overriding WordPress globals is prohibited. Found assignment to $submenu</error>
</file>
</phpcs>

**Comment by mohammaddanish-cedcoss** [comment]
FIxed the $submenu overriding issue but there is one issue left for Use placeholders and $wpdb-&gt;prepare(); found $sql, We are using sql query for migration to make a fast retrieve of the data.

**Comment by mohammaddanish-cedcoss** [comment]
Fixed all phpcs issue
