### ISSUE TITLE
buttons are stuck together

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/woo-refund-and-exchange-lite#65]
WordPress: 6.0.0
WooCommerce: 6.5.1
Description:
buttons are stuck together
![image](https://user-images.githubusercontent.com/85384857/171647292-3a0c7af2-d92b-4e7d-a712-edc1254ea478.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
still an issue:
![image](https://user-images.githubusercontent.com/85384857/171990443-5b2535d5-1179-48d1-b624-86045a7029a3.png)

**Comment by mohammaddanish-cedcoss** [comment]
It is working fine from my side. there must be some cache issue in you site, please clear browser cache and then check it
![screenshot-localhost_10033-2022 06 04-21_06_02](https://user-images.githubusercontent.com/76724269/172012911-7e0bde82-a1e5-4f42-b06d-fbe247fe9930.png)

**Comment by Sukirti-CEDCOSS** [comment]
verified
